version: "3.8"

services:
  pitchlake_starknet:
    platform: linux/amd64
    build:
      context: .
    environment:
      STARKNET_PRIVATE_KEY: ${PITCHLAKE_DEPLOYER_PRIVATE_KEY}
      STARKNET_RPC: ${DEVNET_RPC}
      SIGNER_ADDRESS: ${PITCHLAKE_DEPLOYER_ADDRESS}
      FOSSIL_PROCESSOR_ADDRESS: ${FOSSIL_ADDRESS}
      VAULT_ALPHA: ${VAULT_ALPHA}
      VAULT_STRIKE: ${VAULT_STRIKE}
      ROUND_TRANSITION_DURATION: ${ROUND_TRANSITION_DURATION}
      AUCTION_DURATION: ${AUCTION_DURATION}
      ROUND_DURATION: ${ROUND_DURATION}
      ARGENT_ADDRESS: ${ARGENT_WALLET_ADDRESS}
      ARGENT_SALT: ${ARGENT_WALLET_SALT}
      ARGENT_CONSTRUCTOR_ARG1: ${ARGENT_WALLET_CONSTRUCTOR_ARG1}