[sncast.default]
#url = "http://127.0.0.1:5050/rpc"
url = "https://free-rpc.nethermind.io/sepolia-juno"
accounts-file = ".starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "user1" # replace if desired
